(() => {
"use strict";
const data=JSON.parse(document.getElementById("unit-data").textContent),items=data.vocabulary,$=id=>document.getElementById("speech-"+id);
const key="liveabc-spell-read-v3-unit-"+data.unit;let index=0,recognition=null,state={scores:{},spelled:{}};
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&saved.scores&&saved.spelled)state=saved}catch{}
const panel=document.createElement("section");panel.id="speech";panel.setAttribute("aria-labelledby","speech-title");
panel.innerHTML='<h2 id="speech-title">Part 4 — Spell and Read Aloud · 拼字與朗讀練習</h2><p class="speech-note">Spell the target vocabulary word in its sample sentence. Correct spelling unlocks the next word. The speech-to-text pronunciation check is optional.<br>先完成例句中的目標單字拼字；拼字正確後才能進入下一個單字。朗讀發音檢查為選做。</p><div class="speech-progress-track" aria-hidden="true"><div id="speech-progress-bar"></div></div><div class="speech-meta"><span id="speech-position"></span><span id="speech-completed"></span></div><div class="spell-panel"><h3>✏️ Spell the target word · 拼出目標單字</h3><div id="speech-clue" class="speech-word-title"></div><form id="speech-spell-form"><div id="speech-prompt" class="spell-sentence"></div><button type="submit" id="speech-check-spelling">Check spelling · 檢查拼字</button></form><div id="speech-spell-feedback" class="spell-feedback" role="status" aria-live="polite"></div></div><div id="speech-voice-panel" class="voice-panel hidden"><h3>🔊 聽一聽，再自己念一次（選做）</h3><div id="speech-word" class="speech-word-title"></div><div id="speech-sentence" class="voice-sentence"></div><div class="speech-controls"><button type="button" class="voice-button" id="speech-listen">🔊 再聽一次</button><button type="button" class="voice-button" id="speech-mic">🎤 開始朗讀</button></div><div id="speech-result" class="voice-result" role="status" aria-live="polite"></div></div><div class="speech-navigation"><button type="button" id="speech-prev">← Previous word</button><button type="button" id="speech-next">Next word →</button></div>';
document.querySelector(".actions").before(panel);
const norm=s=>String(s??"").trim().toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g," ");
function targetForm(item){const base=item.word.toLowerCase(),forms=new Set([base,base+"s",base+"es",base+"ed",base+"d",base+"ing"]);const irregular={win:["won"],sell:["sold"],draw:["drew"],lend:["lent"],wake:["woke"],shine:["shone"],step:["stepped"],send:["sent"],become:["became"],catch:["caught"],drop:["dropped"],"fall asleep":["fell asleep"],"make a difference":["made a big difference"],hide:["hid"],rob:["robbed"],understand:["understood"],spend:["spent"],"bring up":["brought up"],choose:["chose"]}[base]||[];irregular.forEach(v=>forms.add(v));if(base.endsWith("e"))forms.add(base.slice(0,-1)+"ing");if(base.endsWith("y")){forms.add(base.slice(0,-1)+"ies");forms.add(base.slice(0,-1)+"ied");}if(base.startsWith("be ")){const lower=item.sample_sentence.toLowerCase(),tail=base.slice(3),phrase=["am ","is ","are ","was ","were ","be ","been ","being "].map(v=>v+tail).find(v=>lower.includes(v));if(phrase){const start=lower.indexOf(phrase);return item.sample_sentence.slice(start,start+phrase.length)}}const sampleLower=item.sample_sentence.toLowerCase(),phraseForm=[...forms].find(v=>v.includes(" ")&&sampleLower.includes(v));if(phraseForm){const start=sampleLower.indexOf(phraseForm);return item.sample_sentence.slice(start,start+phraseForm.length)}const tokens=item.sample_sentence.match(/[A-Za-z]+(?:'[A-Za-z]+)?/g)||[];return tokens.find(token=>forms.has(token.toLowerCase()))||item.word}
function targetRange(item){const answer=targetForm(item),escaped=answer.replace(/[\\^$.*+?()[\]{}|]/g,"\\$&"),match=new RegExp("\\b"+escaped+"\\b","i").exec(item.sample_sentence);return match?{answer:match[0],start:match.index,end:match.index+match[0].length}:{answer,start:0,end:answer.length}}
const canonical=s=>norm(s).replace(/\b(i'm)\b/g,"i am").replace(/\b(can't)\b/g,"cannot").replace(/\b(couldn't)\b/g,"could not").replace(/\b(doesn't)\b/g,"does not").replace(/\b(don't)\b/g,"do not").replace(/\b(wasn't)\b/g,"was not").replace(/\b(isn't)\b/g,"is not").replace(/\b(weren't)\b/g,"were not").replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim();
function distance(a,b){const x=a.split(" ").filter(Boolean),y=b.split(" ").filter(Boolean),d=Array.from({length:x.length+1},()=>Array(y.length+1).fill(0));for(let i=0;i<=x.length;i++)d[i][0]=i;for(let j=0;j<=y.length;j++)d[0][j]=j;for(let i=1;i<=x.length;i++)for(let j=1;j<=y.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(x[i-1]===y[j-1]?0:1));return d[x.length][y.length]}
function similarity(a,b){a=canonical(a);b=canonical(b);if(!a&&!b)return 1;return Math.max(0,1-distance(a,b)/Math.max(a.split(" ").filter(Boolean).length,b.split(" ").filter(Boolean).length,1))}
function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch{}}
function message(text,kind=""){$("result").className="voice-result"+(kind?" "+kind:"");$("result").textContent=text}
function speak(){if(!("speechSynthesis"in window)){message("此瀏覽器無法播放示範語音。","retry");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(items[index].sample_sentence);u.lang="en-US";u.rate=.88;speechSynthesis.speak(u)}
function makePrompt(passed){const item=items[index],target=targetRange(item),box=$("prompt");box.replaceChildren();box.append(document.createTextNode(item.sample_sentence.slice(0,target.start)));const input=document.createElement("input");input.id="speech-spell-input";input.type="text";input.autocomplete="off";input.spellcheck=false;input.setAttribute("aria-label","Spell the target vocabulary word");input.style.width=Math.max(105,Math.min(220,target.answer.length*17+42))+"px";if(passed){input.value=target.answer;input.disabled=true;input.className="spell-correct"}else input.placeholder="________";box.append(input,document.createTextNode(item.sample_sentence.slice(target.end)))}
function render(){window.speechSynthesis?.cancel();recognition?.abort();recognition=null;const item=items[index],passed=state.spelled[index]===targetForm(item).toLowerCase();$("position").textContent="Word "+(index+1)+" / "+items.length;$("progress-bar").style.width=((index+1)/items.length*100)+"%";$("completed").textContent=Object.keys(state.spelled).length+" / "+items.length+" spelled";$("clue").textContent=item.part_of_speech+" · "+item.meaning_zh_tw;makePrompt(passed);$("spell-feedback").className="spell-feedback"+(passed?" good":"");$("spell-feedback").textContent=passed?"✅ 拼字正確！完整句子已解鎖。朗讀為選做，你也可以直接進入下一個單字。":"Type the missing target vocabulary word, then check your spelling. 請填入目標單字。";$("check-spelling").hidden=passed;$("voice-panel").classList.toggle("hidden",!passed);$("word").textContent=passed?targetForm(item)+" · "+item.word:"";$("sentence").textContent=item.sample_sentence;const best=Number(state.scores[index]);message(Number.isFinite(best)?"目前最佳相似度："+best+"%。朗讀為選做。":"按「開始朗讀」後允許使用麥克風，再清楚念完整句子；相似度達 80% 即通過。",Number.isFinite(best)?(best>=80?"good":"retry"):"");$("prev").disabled=index===0;$("next").disabled=!passed||index===items.length-1;$("mic").disabled=false;$("mic").textContent="🎤 開始朗讀";if(!passed)setTimeout(()=>$("spell-input")?.focus(),0)}
function checkSpelling(event){event.preventDefault();const item=items[index],answer=targetForm(item),input=$("spell-input");if(!input.value.trim()){$("spell-feedback").className="spell-feedback retry";$("spell-feedback").textContent="請先填入單字。";input.focus();return}if(norm(input.value)===norm(answer)){state.spelled[index]=answer.toLowerCase();save();render();speak()}else{input.classList.add("spell-wrong");$("spell-feedback").className="spell-feedback retry";$("spell-feedback").textContent="❌ 拼字不正確，請再試一次。";input.select()}}
async function start(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){message("此瀏覽器不支援語音辨識。請使用最新版 Chrome 或 Edge。","retry");return}if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){message("此頁面無法安全使用麥克風。請從 HTTPS 網址開啟，並使用最新版 Chrome 或 Edge。","retry");return}$("mic").disabled=true;$("mic").textContent="🎤 準備中…";message("請允許使用麥克風…");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop())}catch(e){$("mic").disabled=false;$("mic").textContent="🎤 開始朗讀";const m={NotAllowedError:"麥克風權限被封鎖。請在瀏覽器的網站設定中允許麥克風，再試一次。",NotFoundError:"找不到麥克風。請連接麥克風後再試一次。",NotReadableError:"麥克風目前無法使用，可能正被其他程式使用。請關閉其他錄音程式後再試。"};message(m[e.name]||"無法啟動麥克風。請檢查裝置與瀏覽器設定後再試。","retry");return}const sentenceIndex=index,expected=items[index].sample_sentence;recognition=new SR();recognition.lang="en-US";recognition.interimResults=false;recognition.continuous=false;recognition.maxAlternatives=1;$("mic").textContent="🎤 聆聽中…";message("請開始朗讀完整句子…");recognition.onresult=e=>{if(sentenceIndex!==index)return;const heard=e.results[0][0].transcript,score=Math.round(similarity(heard,expected)*100);state.scores[sentenceIndex]=Math.max(Number(state.scores[sentenceIndex])||0,score);save();const box=$("result");box.className="voice-result "+(score>=80?"good":"retry");box.replaceChildren();const heardLine=document.createElement("div");heardLine.append("辨識結果：");const strong=document.createElement("strong");strong.textContent=heard;heardLine.append(strong);const scoreLine=document.createElement("div");scoreLine.textContent="相似度："+score+"%";const outcome=document.createElement("div");outcome.textContent=score>=80?"✅ 朗讀通過（需達 80%）。朗讀為選做。":"❌ 未達 80%。你可以再試一次，或直接前往下一個單字。";box.append(heardLine,scoreLine,outcome)};recognition.onerror=e=>{const m={"no-speech":"沒有偵測到語音。請靠近麥克風並再試一次。","audio-capture":"無法取得麥克風聲音。請檢查麥克風後再試一次。","not-allowed":"語音辨識權限被封鎖。請允許麥克風後再試一次。",network:"語音辨識服務暫時無法連線。請檢查網路後再試一次。"};message(m[e.error]||"語音辨識未完成："+e.error+"。請再試一次。","retry")};recognition.onend=()=>{recognition=null;$("mic").disabled=false;$("mic").textContent="🎤 開始朗讀"};try{recognition.start()}catch{recognition=null;$("mic").disabled=false;$("mic").textContent="🎤 開始朗讀";message("語音辨識無法啟動。請稍候再試一次。","retry")}}
$("spell-form").addEventListener("submit",checkSpelling);$("listen").addEventListener("click",speak);$("mic").addEventListener("click",start);$("prev").addEventListener("click",()=>{if(index>0){index--;render()}});$("next").addEventListener("click",()=>{if(index<items.length-1&&state.spelled[index]){index++;render();$("prompt").tabIndex=-1;$("prompt").focus()}});window.addEventListener("pagehide",()=>{recognition?.abort();window.speechSynthesis?.cancel()});render();
})();
