(() => {
"use strict";
const data=JSON.parse(document.getElementById("unit-data").textContent),items=data.vocabulary,$=id=>document.getElementById("speech-"+id);
const key="liveabc-optional-speech-v2-unit-"+data.unit;let index=0,recognition=null,scores={};
try{scores=JSON.parse(localStorage.getItem(key))||{}}catch{}
const panel=document.createElement("section");panel.id="speech";panel.setAttribute("aria-labelledby","speech-title");
panel.innerHTML='<h2 id="speech-title">Part 4 — Read Aloud · 朗讀練習（選做）</h2><p class="speech-note">You may practice pronunciation or skip to the next word. The check is optional and does not block progress.<br>發音檢查為選做，不論是否練習或達標，都可以前往下一個單字。</p><div class="speech-progress-track" aria-hidden="true"><div id="speech-progress-bar"></div></div><div class="speech-meta"><span id="speech-position"></span><span id="speech-best"></span></div><div class="voice-panel"><h3>🔊 聽一聽，再自己念一次</h3><div id="speech-word" class="speech-word-title"></div><div id="speech-sentence" class="voice-sentence"></div><div class="speech-controls"><button type="button" class="voice-button" id="speech-listen">🔊 再聽一次</button><button type="button" class="voice-button" id="speech-mic">🎤 開始朗讀</button></div><div id="speech-result" class="voice-result" role="status" aria-live="polite"></div></div><div class="speech-navigation"><button type="button" id="speech-prev">← Previous word</button><button type="button" id="speech-next">Next word →</button></div>';
document.querySelector(".actions").before(panel);
const norm=s=>String(s??"").trim().toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g," ");
const canonical=s=>norm(s).replace(/\b(i'm)\b/g,"i am").replace(/\b(can't)\b/g,"cannot").replace(/\b(couldn't)\b/g,"could not").replace(/\b(doesn't)\b/g,"does not").replace(/\b(don't)\b/g,"do not").replace(/\b(wasn't)\b/g,"was not").replace(/\b(isn't)\b/g,"is not").replace(/\b(weren't)\b/g,"were not").replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim();
function distance(a,b){const x=a.split(" ").filter(Boolean),y=b.split(" ").filter(Boolean),d=Array.from({length:x.length+1},()=>Array(y.length+1).fill(0));for(let i=0;i<=x.length;i++)d[i][0]=i;for(let j=0;j<=y.length;j++)d[0][j]=j;for(let i=1;i<=x.length;i++)for(let j=1;j<=y.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(x[i-1]===y[j-1]?0:1));return d[x.length][y.length]}
function similarity(a,b){a=canonical(a);b=canonical(b);if(!a&&!b)return 1;return Math.max(0,1-distance(a,b)/Math.max(a.split(" ").filter(Boolean).length,b.split(" ").filter(Boolean).length,1))}
function message(text,kind=""){$("result").className="voice-result"+(kind?" "+kind:"");$("result").textContent=text}
function save(){try{localStorage.setItem(key,JSON.stringify(scores))}catch{}}
function speak(){if(!("speechSynthesis"in window)){message("此瀏覽器無法播放示範語音。","retry");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(items[index].sample_sentence);u.lang="en-US";u.rate=.88;speechSynthesis.speak(u)}
function render(){window.speechSynthesis?.cancel();recognition?.abort();recognition=null;$("position").textContent="Word "+(index+1)+" / "+items.length;$("progress-bar").style.width=((index+1)/items.length*100)+"%";$("word").textContent=items[index].word+" · "+items[index].part_of_speech+" · "+items[index].meaning_zh_tw;$("sentence").textContent=items[index].sample_sentence;const best=Number(scores[index]);$("best").textContent=Number.isFinite(best)?"Best: "+best+"%":"Optional practice";message(Number.isFinite(best)?"目前最佳相似度："+best+"%。你可以再試一次，或直接前往下一個單字。":"發音檢查為選做。按「開始朗讀」後允許使用麥克風，再清楚念完整句子；相似度達 80% 即通過。",Number.isFinite(best)?(best>=80?"good":"retry"):"");$("prev").disabled=index===0;$("next").disabled=index===items.length-1;$("mic").disabled=false;$("mic").textContent="🎤 開始朗讀"}
async function start(){
 const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
 if(!SR){message("此瀏覽器不支援語音辨識。請使用最新版 Chrome 或 Edge。","retry");return}
 if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){message("此頁面無法安全使用麥克風。請從 HTTPS 網址開啟，並使用最新版 Chrome 或 Edge。","retry");return}
 $("mic").disabled=true;$("mic").textContent="🎤 準備中…";message("請允許使用麥克風…");
 try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop())}
 catch(e){$("mic").disabled=false;$("mic").textContent="🎤 開始朗讀";const m={NotAllowedError:"麥克風權限被封鎖。請在瀏覽器的網站設定中允許麥克風，再試一次。",NotFoundError:"找不到麥克風。請連接麥克風後再試一次。",NotReadableError:"麥克風目前無法使用，可能正被其他程式使用。請關閉其他錄音程式後再試。"};message(m[e.name]||"無法啟動麥克風。請檢查裝置與瀏覽器設定後再試。","retry");return}
 const sentenceIndex=index,expected=items[index].sample_sentence;recognition=new SR();recognition.lang="en-US";recognition.interimResults=false;recognition.continuous=false;recognition.maxAlternatives=1;$("mic").textContent="🎤 聆聽中…";message("請開始朗讀完整句子…");
 recognition.onresult=e=>{if(sentenceIndex!==index)return;const heard=e.results[0][0].transcript,score=Math.round(similarity(heard,expected)*100);scores[sentenceIndex]=Math.max(Number(scores[sentenceIndex])||0,score);save();$("best").textContent="Best: "+scores[sentenceIndex]+"%";const box=$("result");box.className="voice-result "+(score>=80?"good":"retry");box.replaceChildren();const heardLine=document.createElement("div");heardLine.append("辨識結果：");const strong=document.createElement("strong");strong.textContent=heard;heardLine.append(strong);const scoreLine=document.createElement("div");scoreLine.textContent="相似度："+score+"%";const outcome=document.createElement("div");outcome.textContent=score>=80?"✅ 朗讀通過（需達 80%）。你也可以繼續練習或前往下一個單字。":"❌ 未達 80%。你可以再聽一次並重新朗讀，或直接前往下一個單字。";box.append(heardLine,scoreLine,outcome)};
 recognition.onerror=e=>{const m={"no-speech":"沒有偵測到語音。請靠近麥克風並再試一次。","audio-capture":"無法取得麥克風聲音。請檢查麥克風後再試一次。","not-allowed":"語音辨識權限被封鎖。請允許麥克風後再試一次。",network:"語音辨識服務暫時無法連線。請檢查網路後再試一次。"};message(m[e.error]||"語音辨識未完成："+e.error+"。請再試一次。","retry")};
 recognition.onend=()=>{recognition=null;$("mic").disabled=false;$("mic").textContent="🎤 開始朗讀"};
 try{recognition.start()}catch{recognition=null;$("mic").disabled=false;$("mic").textContent="🎤 開始朗讀";message("語音辨識無法啟動。請稍候再試一次。","retry")}
}
$("listen").addEventListener("click",speak);$("mic").addEventListener("click",start);$("prev").addEventListener("click",()=>{if(index>0){index--;render()}});$("next").addEventListener("click",()=>{if(index<items.length-1){index++;render();$("sentence").tabIndex=-1;$("sentence").focus()}});window.addEventListener("pagehide",()=>{recognition?.abort();window.speechSynthesis?.cancel()});render();
})();